"""M1b filesystem probe for native Windows. No LLM, lesson or audio is run.

Test only disposable fixtures. This is NOT full agent/context isolation.
Reference: openai/codex, tag rust-v0.153.4, cli/src/{lib,debug_sandbox}.rs.
"""
from __future__ import annotations

import errno
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import uuid

ROOT = Path(__file__).resolve().parents[1]
ROLES = ("author", "judge", "arbiter")
PREFIX = "WEBINAR_BOUNDARY_RESULT="
PROFILE = "webinar_boundary_probe"

# This code is run directly inside the sandbox, not generated by a model.
# Each path belongs to a disposable directory created by this program.
PROBE = r'''
import errno,json,os,pathlib,sys
checks=json.loads(sys.argv[1])
results={}
for name, item in checks.items():
    path=pathlib.Path(item["path"])
    try:
        if item["operation"] == "read":
            with path.open("rb") as handle:
                handle.read()
        elif item["operation"] == "open_write":
            # Prove write access without changing or truncating the fixture.
            fd=os.open(str(path), os.O_WRONLY)
            os.close(fd)
        elif item["operation"] == "create":
            with path.open("x", encoding="utf-8") as handle:
                handle.write("SYNTHETIC_OUTPUT\n")
        else:
            raise ValueError("unknown probe operation")
        result={"outcome":"ALLOWED"}
    except OSError as error:
        denied=isinstance(error, PermissionError) or error.errno in (errno.EACCES,errno.EPERM)
        result={"outcome":"DENIED" if denied else "ERROR",
                "errno":error.errno,"winerror":getattr(error,"winerror",None),
                "exception":type(error).__name__}
    results[name]=result
print("WEBINAR_BOUNDARY_RESULT="+json.dumps(results), flush=True)
'''


def toml(value: object) -> str:
    """Encode the small subset needed for an inline TOML config override."""
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dict):
        return "{" + ", ".join(toml(k) + "=" + toml(v) for k, v in value.items()) + "}"
    raise TypeError(f"Unsupported TOML value: {type(value).__name__}")


def find_cli() -> list[str]:
    native = shutil.which("codex.exe")
    if native:
        return [native]
    shim = shutil.which("codex.cmd") or shutil.which("codex")
    if not shim:
        raise RuntimeError("Codex is not in PATH.")
    entry = Path(shim).resolve().parent / "node_modules/@openai/codex/bin/codex.js"
    node = shutil.which("node.exe") or shutil.which("node")
    if not entry.is_file() or not node:
        raise RuntimeError("Cannot resolve the npm Codex executable. No shell fallback was used.")
    return [node, str(entry)]


def environment() -> dict[str, str]:
    allowed = {
        "PATH", "PATHEXT", "SYSTEMROOT", "WINDIR", "COMSPEC", "SYSTEMDRIVE",
        "PROGRAMFILES", "PROGRAMFILES(X86)", "PROGRAMDATA", "APPDATA", "LOCALAPPDATA",
        "USERPROFILE", "HOMEDRIVE", "HOMEPATH", "HOME", "USERNAME", "USER",
        "TEMP", "TMP", "TMPDIR", "CODEX_HOME", "LANG", "TERM",
    }
    # Keep the installed sandbox location. Never copy, print or parse auth.json.
    return {k: v for k, v in os.environ.items() if k.upper() in allowed}


def execute(args: list[str], cwd: Path, timeout: int = 90) -> subprocess.CompletedProcess:
    with subprocess.Popen(args, cwd=cwd, env=environment(), stdin=subprocess.DEVNULL,
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
                          encoding="utf-8", errors="replace", shell=False) as process:
        try:
            out, err = process.communicate(timeout=timeout)
        except BaseException:
            if os.name == "nt" and process.poll() is None:
                try:
                    subprocess.run(["taskkill", "/PID", str(process.pid), "/T", "/F"],
                                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                                   timeout=10, check=False)
                except (OSError, subprocess.TimeoutExpired):
                    pass
            if process.poll() is None:
                process.kill()
            process.wait(timeout=10)
            raise
        return subprocess.CompletedProcess(args, process.returncode, out, err)


def create_fixtures(root: Path) -> None:
    (root / "shared").mkdir()
    (root / "shared/evidence.txt").write_text("SYNTHETIC_EVIDENCE\n", encoding="utf-8")
    (root / "shared/rubric.txt").write_text("SYNTHETIC_RUBRIC\n", encoding="utf-8")
    (root / "shared/approval.txt").write_text("NOT_APPROVED\n", encoding="utf-8")
    (root / "unlisted").mkdir()
    (root / "unlisted/note.txt").write_text("SYNTHETIC_UNLISTED\n", encoding="utf-8")
    for role in ROLES:
        (root / role / "out").mkdir(parents=True)
        (root / role / "private.txt").write_text("SYNTHETIC_PRIVATE\n", encoding="utf-8")
        (root / role / "out/existing.txt").write_text("SYNTHETIC_REPORT\n", encoding="utf-8")


def probes(root: Path, role: str) -> dict:
    def item(path: Path, operation: str, expected: str) -> dict:
        return {"path": str(path), "operation": operation, "expected": expected}
    checks = {
        "evidence_read": item(root / "shared/evidence.txt", "read", "ALLOWED"),
        "rubric_read": item(root / "shared/rubric.txt", "read", "ALLOWED"),
        "own_private_read": item(root / role / "private.txt", "read", "ALLOWED"),
        "own_output_create": item(root / role / "out/new.txt", "create", "ALLOWED"),
        "rubric_write": item(root / "shared/rubric.txt", "open_write", "DENIED"),
        "approval_write": item(root / "shared/approval.txt", "open_write", "DENIED"),
        "evidence_write": item(root / "shared/evidence.txt", "open_write", "DENIED"),
        "unlisted_read": item(root / "unlisted/note.txt", "read", "DENIED"),
    }
    for other in ROLES:
        if other != role:
            checks[other + "_private_read"] = item(root / other / "private.txt", "read", "DENIED")
            checks[other + "_report_write"] = item(root / other / "out/existing.txt", "open_write", "DENIED")
    return checks


def permission_config(root: Path, role: str) -> dict:
    fs = {":minimal": "read", str(Path(sys.base_prefix).resolve()): "read",
          str(Path(sys.prefix).resolve()): "read", str(root / "shared"): "read",
          str(root / role): "read", str(root / role / "out"): "write"}
    # Explicit private/report exclusions plus an unlisted-read control.
    for other in ROLES:
        if other != role:
            fs[str(root / other)] = "deny"
    return {PROFILE: {"filesystem": fs, "network": {"enabled": False}}}


def sandbox_command(cli: list[str], root: Path, role: str) -> list[str]:
    return [*cli, "-c", "permissions=" + toml(permission_config(root, role)),
            "-c", 'approval_policy="never"', "sandbox", "-P", PROFILE,
            "--include-managed-config", "-C", str(root / role), "--",
            sys.executable, "-I", "-S", "-B", "-c", PROBE,
            json.dumps(probes(root, role), ensure_ascii=True)]


def parse_result(output: str, expected: dict) -> dict:
    lines = [line[len(PREFIX):] for line in output.splitlines() if line.startswith(PREFIX)]
    if len(lines) != 1:
        raise ValueError("Probe did not return exactly one result; this is NOT a successful denial test.")
    result = json.loads(lines[0])
    if not isinstance(result, dict) or set(result) != set(expected):
        raise ValueError("Probe result does not match the requested checks.")
    for name, value in result.items():
        if not isinstance(value, dict) or value.get("outcome") not in ("ALLOWED", "DENIED", "ERROR"):
            raise ValueError("Invalid probe result: " + name)
    return result


def main() -> int:
    if os.name != "nt":
        print("This live probe targets native Windows. Use unit tests on other systems.")
        return 2
    run_dir = ROOT / "runs" / "boundary-probe" / uuid.uuid4().hex
    run_dir.mkdir(parents=True)
    report = {"filesystem_probe": "ERROR", "roles": {}, "llm_called": False,
              "instruction_isolation_verified": False, "isolation_verified": False,
              "production_ready": False, "network_isolation_tested": False}
    try:
        cli = find_cli()
        with tempfile.TemporaryDirectory(prefix="webinar-boundary-") as tmp:
            root = Path(tmp).resolve()
            version = execute([*cli, "--version"], root, 30)
            if version.returncode:
                raise RuntimeError("Cannot obtain Codex version.")
            report["cli_version"] = version.stdout.strip()
            if report["cli_version"] != "codex-cli 0.153.4":
                raise RuntimeError("Probe is pinned to verified CLI 0.153.4; no unsupported flags were tried.")
            create_fixtures(root)
            for role in ROLES:
                checks = probes(root, role)
                # Positive control: every target exists and is accessible outside the sandbox.
                baseline = execute([sys.executable, "-I", "-S", "-B", "-c", PROBE,
                                    json.dumps(checks)], root / role, 20)
                before = parse_result(baseline.stdout, checks)
                if baseline.returncode or any(v["outcome"] != "ALLOWED" for v in before.values()):
                    raise RuntimeError("Baseline failed for " + role + "; cannot infer sandbox enforcement.")
                (root / role / "out/new.txt").unlink()
                result = execute(sandbox_command(cli, root, role), root / role)
                (run_dir / (role + "-stdout.log")).write_text(result.stdout, encoding="utf-8")
                (run_dir / (role + "-stderr.log")).write_text(result.stderr, encoding="utf-8")
                if result.returncode:
                    report["roles"][role] = {"status": "ERROR", "exit_code": result.returncode,
                                              "message": result.stderr[-2000:]}
                    continue
                actual = parse_result(result.stdout, checks)
                rows = {name: {**value, "expected": checks[name]["expected"],
                                "pass": value["outcome"] == checks[name]["expected"]}
                        for name, value in actual.items()}
                ok = all(row["pass"] for row in rows.values())
                report["roles"][role] = {"status": "PASS" if ok else "FAIL", "checks": rows}
            if len(report["roles"]) == len(ROLES):
                states = [row["status"] for row in report["roles"].values()]
                report["filesystem_probe"] = "ERROR" if "ERROR" in states else ("PASS" if all(s == "PASS" for s in states) else "FAIL")
    except (OSError, RuntimeError, ValueError, subprocess.SubprocessError) as error:
        report["error"] = str(error)
    finally:
        path = run_dir / "summary.json"
        path.write_text(json.dumps(report, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
        print(json.dumps(report, indent=2, ensure_ascii=True))
        print("Report: " + str(path))
    return 0 if report["filesystem_probe"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
